name: CI

on:
  pull_request_target

permissions:
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
      FLAG: ${{ secrets.FLAG }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check commit author
        run: |
          author=$(git log -1 --format='%an')
          if [ "$author" != "john" ]; then
            echo "Only 'john' is allowed to run the CI through commits!"
            exit 1
          fi

      - uses: actions/setup-node@v4

      - run: npm install
      - run: npm test
